version : '3'
services:
  nginx:
    image: nginx
    container_name: laradoceract_nginx
    build:
      context: .
      dockerfile: infra/dev/docker/nginx/Dockerfile
    ports:
        - "8080:80"
    volumes:
        - ./infra/dev/docker/nginx/conf.d:/etc/nginx/conf.d
    links:
        - php
  php:
    image: php:7-fpm
    container_name: laradoceract_php
    build:
      context: .
      dockerfile: infra/dev/docker/fpm/Dockerfile
    volumes:
      - ./backend:/var/www/html